BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-streaming"
BBFILE_PATTERN_meta-streaming = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-streaming = "6"

LAYERSERIES_COMPAT_meta-streaming = "scarthgap"
